type = 'CameraErrorSelector'
target_camera_number = 5
triangulator = dict(
    type='AniposelibTriangulator',
    camera_parameters=[],
    camera_convention='opencv',
    logger=None)
verbose = True
logger = None
