name: auto reply
on:
  issues:
    types: [labeled]
jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v1.2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. welcome to comment here , we will reply you as soon.
            你好 @${{ github.event.issue.user.login }}，非常欢迎在此讨论，我们会尽快确认并回复你~~
